### ISSUE TITLE
Recaptcha Solver 2

### ISSUE THREAD

**Issue by webchk** [Sadzurami/steam-sessions-creator#3]
I tried to configure and test your software, however it closes when you press ok, it loads for a few seconds and hangs and closes, I would like to know how to configure it, I believe it is the api or proxy that is misconfigured, could you leave a video showing how configure correctly. if you have telegram please send me
I didn't find any other way to contact you
https://github.com/Sadzurami/recaptcha-v2-solver

**Comment by Sadzurami** [comment]
That's not `recaptcha-solver` repository.
However, app that you mean no longer supported by me.

**Comment by Sadzurami** [comment]
That app no longer supported by me.
