### ISSUE TITLE
Вывод плохих аккаунтов

### ISSUE THREAD

**Issue by Plimm** [Sadzurami/steam-sessions-creator#4]
Сделать какой-то документ после того как программа закончит работу, который покажет списко плохихи аккаунтов, для выяснения причин что с ними не так

**Comment by Sadzurami** [comment]
> Сделать какой-то документ после того как программа закончит работу, который покажет списко плохихи аккаунтов, для выяснения причин что с ними не так

Не вижу смысла в этом. Можно запустить команду повторно, созданные сессии будут пропущены, ошибочные созданы.

Если после повторного запуска не все были созданы, можно посмотреть последний лог файл, в котором будет информация о причине ошибки.

**Comment by Sadzurami** [comment]
@Plimm 

Добавлено в релизе 2.2.6
https://github.com/Sadzurami/steam-sessions-creator/releases/tag/2.2.6
